#!/bin/bash
cd /bin
echo "vncserver -geometry 1555x600" > vncs
chmod a+x vncs

cd
mkdir .vnc

echo '#!/bin/sh
autocutsel -fork
xrdb $HOME/.Xresources
gnome-control-center "$VNCDESKTOP Desktop" &
xsetroot -solid grey
export XKL_XMODMAP_DISABLE=1
export XDG_CURRENT_DESKTOP="GNOME-Flashback:Unity"
export XDG_MENU_PREFIX="gnome-flashback-"
unset DBUS_SESSION_BUS_ADDRESS
gnome-session --session=gnome-flashback-metacity --disable-acceleration-check --debug &' > .vnc/xstartup

cd .vnc
chmod +x xstartup

sudo service dbus start
